accent: blue

breadcrumbs: p-4 pb-0 md:p-8 md:pb-0

buttons:
  accents:
    primary: bg-%accent%-500 focus:bg-%accent%-700 hover:bg-%accent%-600 border border-%accent%-500 text-white
    secondary: bg-gray-500 focus:bg-gray-700 hover:bg-gray-600 border border-gray-500 text-white
    tertiary:
  button: sm:mr-2 my-1 focus:outline-none rounded w-full sm:w-auto
  directives:
  size:
    md: py-2 px-4
    sm: py-1 px-3

card: bg-white overflow-hidden mb-4 sm:mb-6 md:mb-8 rounded-lg shadow-md

container: m-auto md:w-3/4 xl:w-2/3

content: pt-4 px-4 md:pt-6 md:px-8

fields:
  default:
    output: flex-1
  boolean:
    container: inline-flex items-center justify-center px-2 py-0 text-xs font-semibold tracking-wider leading-loose uppercase rounded-full border
    variants:
      danger: bg-red-100 border-red-200 text-red-800
      success: bg-green-100 border-green-200 text-green-800
  timestamp:
    container: text-sm
    time:
      container: xl:inline hidden
      value: text-gray-500

flash:
  caption: text-sm
  container: pt-6 pb-5 px-4 md:px-8 xl:px-12
  highlight: font-semibold
  icon: mr-1 text-lg
  message:
    container: flex items-center
    text: font-light text-xl
  variants:
    icon:
      danger:
      success:
    theme:
      danger: bg-red-100 text-red-700
      success: bg-green-100 text-green-700

form:
  fields:
    container: flex flex-wrap md:pb-2
    field:
      container: w-full
      error: block font-normal pt-2 md:pt-3 text-red-500 text-xs
      input: appearance-none block bg-gray-100 focus:bg-gray-500 border border-gray-300 focus:border-gray-500 leading-tight focus:outline-none py-3 px-4 rounded text-gray-700 focus:text-white w-full
  label:
    container: block mb-6
    text: block font-medium mb-2

index:
  list:
    field: truncate py-4 pl-5 md:pl-6 lg:pl-8
    header:
      container: bg-gray-100 flex font-medium items-center text-base
      field: mt-1
    invokers:
      invokers: group-hover:block hidden
      container: inline-flex -mr-2 w-20
    row: hover:bg-gray-100 border-t flex group items-center

invokers:
  default: cursor-pointer flex items-center justify-between px-4 py-3
  directives:
  accents:
    danger: hover:bg-red-100 hover:text-red-700
    default: hover:bg-gray-200 hover:text-%accent%-500
    success: hover:bg-green-100 hover:text-green-600
    warning: hover:bg-orange-100 hover:text-orange-600
  icons:
    default:
    edit:
    duplicate:
    show:
    publish:
    unpublish:
    destroy:

link:
  accent: text-%accent%-500
  default: hover:underline
  underline: underline

padding: p-4 md:p-6 lg:p-8

views:
  layout:
    sections:
      breadcrumbs: backend.breadcrumbs
      content: backend.content
      flash: backend.flash
    view: layouts.backend
